# Supernal Coding Configuration
# Generated: 2025-10-26T22:48:00.000Z

[project]
name = "@supernal-interface"
type = "requirements-driven"
git_root = "/Users/ianderrington/git/supernal-nova/platform/services/user-management/packages/@supernal-interface"
current_branch = "main"

[paths]
# Auto-detected paths based on repository structure
auto_detect = true
git_root_detection = true
project_type = "auto_detected"

# Resolved directory paths
requirements = "requirements"
kanban = "kanban"
templates = "templates"
tests = "tests"

# Fallback directories for path resolution
fallback_directories = [
  "requirements", "reqs", "specs", "docs/requirements",
  "kanban", "tasks", "workflow", "supernal-coding/kanban",
  "workflow-rules", "rules", "workflow", "supernal-coding/workflow-rules",
  "templates", "template", "supernal-coding/templates",
  "tests", "test", "spec", "tests/requirements",
  "docs", "documentation", "supernal-coding/docs",
  "supernal-coding", "config", ".supernal-coding"
]

[requirements]
# Requirements management configuration
directory = "requirements"
template = "requirement-template.md"
auto_numbering = true
validation = true

[kanban]
# Kanban workflow configuration
directory = "kanban"
columns = ["BRAINSTORM", "PLANNING", "TODO", "DOING", "BLOCKED", "DONE"]
auto_move = true
track_progress = true

[init]
repository_analysis = true
auto_configure_paths = true
interactive_setup = true
validate_structure = true

[init.detection]
detect_requirements_dir = true
detect_kanban_dir = true
detect_workflow_rules = true
detect_templates = true
detect_tests_dir = true
detect_docs_dir = true
detect_config_dir = true

[validation]
validate_git_repository = true
validate_path_resolution = true
validate_structure_compatibility = true
auto_fix_common_issues = true

[compatibility]
multi_repo_support = true
dynamic_path_resolution = true
auto_detect_structure = true
fallback_mechanisms = true

[dashboard]
# Dashboard configuration
enabled = true
port = 3001
auto_refresh = true
embedded = true

# Repository-specific overrides (if needed)
[overrides]
# Uncomment and customize if needed:
# requirements_dir = "custom/requirements"
# kanban_dir = "custom/kanban"
# workflow_rules_dir = "custom/workflow-rules"
