#!/usr/bin/env node

/**
 * 🤖 GENERATED FILE - DO NOT EDIT MANUALLY
 * 
 * This dashboard API server was generated by: sc dashboard init
 * Generated on: 2025-10-26T21:47:17.255Z
 * Template version: 1.0.0
 * 
 * To update this dashboard:
 * - Run: sc dashboard update  
 * - Or regenerate: sc dashboard init -y --force
 * 
 * Source template: supernal-code-package/templates/dashboard/
 */

const express = require('express');
const path = require('path');
const fs = require('fs');
const cors = require('cors');

const app = express();

// Smart port detection
async function getAvailablePort() {
  const { findAvailablePort } = require('../scripts/port-scanner');
  const preferredPort = parseInt(process.env.DASHBOARD_PORT || process.env.PORT || '3000');
  
  try {
    const availablePort = await findAvailablePort(preferredPort);
    if (availablePort !== preferredPort) {
      console.log(`⚠️  Port ${preferredPort} was busy, using port ${availablePort}`);
    }
    return availablePort;
  } catch (error) {
    console.error('❌ Could not find available port:', error.message);
    return preferredPort; // Fallback to preferred port
  }
}

// Middleware
app.use(cors());
app.use(express.json());
// Serve static files (HTML, CSS, JS)
app.use(express.static(__dirname));

// Load configuration and get directory paths
// Use the correct project root for supernal-coding
const projectRoot = path.join(__dirname, '..');
let config;

try {
  const { getConfig } = require(path.join(projectRoot, 'scripts/config-loader'));
  config = getConfig(projectRoot);
  config.load(); // Ensure config is loaded
} catch (error) {
  console.warn('⚠️  Could not load config, using default paths');
  config = {
    getRequirementsDirectory: () => 'supernal-coding/requirements',
    getKanbanBaseDirectory: () => 'supernal-coding/kanban'
  };
}

// Use template-configured paths for this project
const REQUIREMENTS_DIR = path.join(projectRoot, 'supernal-coding/requirements');
const KANBAN_DIR = path.join(projectRoot, 'supernal-coding/kanban');

let KanbanParser;
try {
  KanbanParser = require(path.join(projectRoot, 'documentation/static/dashboard/src/services/kanbanParser'));
} catch (error) {
  console.warn('⚠️  Could not load KanbanParser, using mock data');
  KanbanParser = class MockKanbanParser {
    scanKanbanTasks() { return []; }
    getKanbanStats() { return { total: 0, epics: 0 }; }
    linkTasksToRequirements() { return []; }
  };
}

// Initialize services
const kanbanParser = new KanbanParser(KANBAN_DIR);

/**
 * Parse a requirement file and extract metadata
 */
function parseRequirement(filePath) {
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        const fileName = path.basename(filePath, '.md');
        
        // Extract YAML front matter
        const yamlMatch = content.match(/^---\n([\s\S]*?)\n---/);
        let priority = 'Medium';
        let priorityScore = 5;
        
        if (yamlMatch) {
            const yamlContent = yamlMatch[1];
            const priorityMatch = yamlContent.match(/priority:\s*(.+)/);
            const scoreMatch = yamlContent.match(/priorityScore:\s*(\d+)/);
            
            if (priorityMatch) priority = priorityMatch[1].trim();
            if (scoreMatch) priorityScore = parseInt(scoreMatch[1]);
        }
        
        // Extract title from markdown
        const titleMatch = content.match(/# (.+)/);
        const title = titleMatch ? titleMatch[1].replace(/REQ-\d+:\s*/, '') : fileName;
        
        // Extract category from file path
        const relativePath = path.relative(REQUIREMENTS_DIR, filePath);
        const category = path.dirname(relativePath);
        
        // Extract status from content
        const statusMatch = content.match(/\*\*Status\*\*:\s*(.+)/);
        const status = statusMatch ? statusMatch[1].trim() : 'Planning';
        
        // Extract req ID
        const reqIdMatch = fileName.match(/(req-\d+)/i) || title.match(/(REQ-\d+)/i);
        const reqId = reqIdMatch ? reqIdMatch[1].toUpperCase() : fileName.toUpperCase();
        
        return {
            id: reqId,
            title: title,
            category: category === '.' ? 'core' : category,
            priority: priority,
            priorityScore: priorityScore,
            status: status,
            filePath: filePath
        };
    } catch (error) {
        console.error(`Error parsing requirement ${filePath}:`, error.message);
        return null;
    }
}

/**
 * Scan requirements directory and parse all requirement files
 */
function loadRequirements() {
    const requirements = [];
    
    try {
        // Validate frontmatter before loading
        let validator;
        try {
            const FrontmatterValidator = require(path.join(projectRoot, 'supernal-code-package/lib/cli/utils/frontmatter-validator'));
            validator = new FrontmatterValidator();
            const validation = validator.validateRequirements(REQUIREMENTS_DIR);
            
            if (!validation.valid) {
                console.log('⚠️  Frontmatter validation issues detected in dashboard:');
                console.log(`   ${validation.summary.errorCount} errors, ${validation.summary.warningCount} warnings`);
                console.log(`   Files with errors: ${validation.summary.filesWithErrors.join(', ')}`);
            }
        } catch (error) {
            console.warn('⚠️  Could not load frontmatter validator');
        }
        
        function scanDir(dir) {
            if (!fs.existsSync(dir)) {
                console.warn(`⚠️  Directory not found: ${dir}`);
                return;
            }
            
            const items = fs.readdirSync(dir);
            
            for (const item of items) {
                const fullPath = path.join(dir, item);
                const stat = fs.statSync(fullPath);
                
                if (stat.isDirectory()) {
                    scanDir(fullPath);
                } else if (item.endsWith('.md') && item.match(/req-\d+/i)) {
                    const requirement = parseRequirement(fullPath);
                    if (requirement) {
                        requirements.push(requirement);
                    }
                }
            }
        }
        
        scanDir(REQUIREMENTS_DIR);
        
    } catch (error) {
        console.error('Error loading requirements:', error.message);
    }
    
    return requirements;
}

/**
 * Generate dashboard statistics
 */
function generateStats(requirements) {
    const stats = requirements.reduce((acc, req) => {
        const priority = req.priority.toLowerCase();
        acc[priority] = (acc[priority] || 0) + 1;
        return acc;
    }, {});
    
    const totalReqs = requirements.length;
    const completedReqs = requirements.filter(req => 
        req.status.toLowerCase().includes('done') || 
        req.status.toLowerCase().includes('complete')
    ).length;
    
    return {
        total: totalReqs,
        completed: completedReqs,
        progress: totalReqs > 0 ? Math.round((completedReqs / totalReqs) * 100) : 0,
        critical: stats.critical || 0,
        high: stats.high || 0,
        medium: stats.medium || 0,
        low: stats.low || 0
    };
}

// Serve dashboard HTML at root
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'index.html'));
});

// API info endpoint
app.get('/api', (req, res) => {
    res.json({
        name: '@supernal-interface API',
        version: '1.0.0',
        status: 'running',
        endpoints: {
            requirements: '/api/requirements',
            stats: '/api/stats',
            kanban: '/api/kanban',
            health: '/api/health'
        }
    });
});

app.get('/api/requirements', (req, res) => {
    const requirements = loadRequirements();
    res.json(requirements);
});

app.get('/api/stats', (req, res) => {
    const requirements = loadRequirements();
    const stats = generateStats(requirements);
    res.json(stats);
});

app.get('/api/kanban', (req, res) => {
    try {
        const kanbanData = kanbanParser.scanKanbanTasks();
        res.json(kanbanData);
    } catch (error) {
        console.error('Error loading kanban data:', error.message);
        res.json([]);
    }
});

app.get('/api/kanban/stats', (req, res) => {
    try {
        const kanbanStats = kanbanParser.getKanbanStats();
        res.json(kanbanStats);
    } catch (error) {
        console.error('Error loading kanban stats:', error.message);
        res.json({ total: 0, epics: 0 });
    }
});

app.get('/api/hierarchy', (req, res) => {
    try {
        const requirements = loadRequirements();
        const hierarchy = kanbanParser.linkTasksToRequirements(requirements);
        res.json(hierarchy);
    } catch (error) {
        console.error('Error loading hierarchy:', error.message);
        res.json([]);
    }
});

app.get('/api/health', (req, res) => {
    const requirements = loadRequirements();
    let kanbanStats = { total: 0, epics: 0 };
    
    try {
        kanbanStats = kanbanParser.getKanbanStats();
    } catch (error) {
        console.warn('Could not load kanban stats for health check');
    }
    
    res.json({ 
        status: 'healthy', 
        timestamp: new Date().toISOString(),
        requirements_found: requirements.length,
        kanban_tasks_found: kanbanStats.total,
        epics_found: kanbanStats.epics
    });
});

// Start server with smart port detection
async function startServer() {
  const PORT = await getAvailablePort();
  
  app.listen(PORT, () => {
      console.log(`🚀 @supernal-interface Dashboard API Server running at:`);
      console.log(`   Local:   http://localhost:${PORT}`);
      console.log(`   Network: http://0.0.0.0:${PORT}`);
      console.log(`\n📊 API Endpoints:`);
      console.log(`   GET /api/requirements - Get all requirements`);
      console.log(`   GET /api/stats       - Get dashboard statistics`);
      console.log(`   GET /api/health      - Health check`);
      console.log(`\n🔄 Auto-scanning requirements from: ${REQUIREMENTS_DIR}`);
      
      // Initial load to verify setup
      const requirements = loadRequirements();
      console.log(`\n✅ Found ${requirements.length} requirements`);
      
      if (requirements.length > 0) {
          const stats = generateStats(requirements);
          console.log(`📈 Progress: ${stats.progress}% (${stats.completed}/${stats.total} complete)`);
          console.log(`🎯 Priority Distribution: ${stats.critical} Critical, ${stats.high} High, ${stats.medium} Medium, ${stats.low} Low`);
      }
  });
}

// Start the server
startServer().catch(console.error);

// Handle graceful shutdown
process.on('SIGINT', () => {
    console.log('\n🛑 Shutting down dashboard server...');
    process.exit(0);
});

module.exports = { loadRequirements, generateStats, parseRequirement }; 